# Generated by Django 6.0.1 on 2026-01-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_student_email_student_father_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenrollment',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='student',
        ),
    ]
