# Generated by Django 6.0.1 on 2026-01-18 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_studentenrollment_batch_studentenrollment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.batch'),
        ),
    ]
