# Generated by Django 6.0.1 on 2026-01-18 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_studentenrollment_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='start_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.student'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('student',), name='uniq_active_enrollment_per_student'),
        ),
    ]
