# Generated by Django 6.0.1 on 2026-01-18 11:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.institution')),
            ],
        ),
    ]
